apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-webapp 
spec:
  selector:
    matchLabels: 
      app: sa-webapp
  replicas: 3 
  minReadySeconds: 15 
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata: 
      labels:
        app: sa-webapp 
    spec:
      containers:
      - image: rikinparekh/nsawa:minikube2
        imagePullPolicy: Always 
        name: sa-webapp
        env:
        - name: SA_LOGIC_API_URL 
          value: "http://172.17.0.6:5001"
        ports:
        - containerPort: 8080